defaults:
  - mppi: multi-jackal

goal: [2.0, 0.0, -2.0, 0.0]
render: true
n_steps: 1000
nx: 8

dt: 0.1

actors: ['jackal', 'jackal', 'xaxis', 'yaxis']
initial_actor_positions: [[-2.0, 0.0, 0.0], [4.0, 0.0, 3.1415]]
